apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: innovatech-cluster
  region: us-east-1
  version: "1.31"

iam:
  serviceRoleARN: arn:aws:iam::794860266885:role/LabRole

vpc:
  id: vpc-07a0ffde3f8d510dc
  subnets:
    public:
      us-east-1a: { id: subnet-0a5b6b9f33eb9fb8f }
      us-east-1b: { id: subnet-02bc61731ed2fd002 }

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    privateNetworking: false
    iam:
      instanceRoleARN: arn:aws:iam::794860266885:role/LabRole
