server.port=8084
spring.application.name=ms-analiticas

spring.datasource.url=jdbc:mysql://localhost:3306/db_recursos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none

# Actuator - Health checks para EKS
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
