apiVersion: v1
kind: ConfigMap
metadata:
  name: innovatech-config
  namespace: innovatech
data:
  # URLs de datasource: una INSTANCIA RDS dedicada por microservicio
  AUTENTICACION_DB_URL: "jdbc:mysql://innovatech-db-autenticacion.cq5lexhdh84h.us-east-1.rds.amazonaws.com:3306/db_autenticacion?createDatabaseIfNotExist=true"
  RECURSOS_DB_URL: "jdbc:mysql://innovatech-db-recursos.cq5lexhdh84h.us-east-1.rds.amazonaws.com:3306/db_recursos?createDatabaseIfNotExist=true"
  GESTION_PROYECTOS_DB_URL: "jdbc:mysql://innovatech-db-gestion.cq5lexhdh84h.us-east-1.rds.amazonaws.com:3306/db_gestion_proyectos?createDatabaseIfNotExist=true"
  ANALITICAS_DB_URL: "jdbc:mysql://innovatech-db-analiticas.cq5lexhdh84h.us-east-1.rds.amazonaws.com:3306/db_analiticas?createDatabaseIfNotExist=true"

  SPRING_DATASOURCE_USERNAME: "admin"

  # URLs internas usadas por ms-api-gateway para enrutar a cada microservicio
  AUTH_SERVICE_URL: "http://ms-autenticacion:8081"
  RECURSOS_COLABORACIONES_SERVICE_URL: "http://ms-recursos-colaboraciones:8082"
  GESTION_PROYECTOS_SERVICE_URL: "http://ms-gestion-proyectos:8083"
  ANALITICAS_SERVICE_URL: "http://ms-analiticas:8084"
  GANTT_SERVICE_URL: "http://ms-carta-gantt:8085"

  # Origen permitido para CORS
  CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://innovatech-frontend.s3-website-us-east-1.amazonaws.com"
