apiVersion: v1
kind: Service
metadata:
  name: ms-autenticacion
  namespace: innovatech
spec:
  selector:
    app: ms-autenticacion
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ms-recursos-colaboraciones
  namespace: innovatech
spec:
  selector:
    app: ms-recursos-colaboraciones
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: ms-gestion-proyectos
  namespace: innovatech
spec:
  selector:
    app: ms-gestion-proyectos
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: ms-analiticas
  namespace: innovatech
spec:
  selector:
    app: ms-analiticas
  ports:
    - port: 8084
      targetPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: ms-carta-gantt
  namespace: innovatech
spec:
  selector:
    app: ms-carta-gantt
  ports:
    - port: 8085
      targetPort: 8085
---
# LoadBalancer publico - punto de entrada del backend (ver FASE 5.4 de la guia)
apiVersion: v1
kind: Service
metadata:
  name: ms-api-gateway
  namespace: innovatech
spec:
  type: LoadBalancer
  selector:
    app: ms-api-gateway
  ports:
    - port: 80
      targetPort: 8080
